name: KhangSMP-MoneyShort
version: 1.0.0-PREMIUM
main: vn.pika.moneyshort.MoneyShort
api-version: "1.20"
author: KhangSMP
description: Plugin rut gon tien te doc quyen - KhangSMP Premium Edition
depend: [Vault, PlaceholderAPI]
